### PR TITLE
Fix javascript error on log out

### LINKED ISSUE #2888: JavaScript error on logout
### Expected
Logging out should not cause a JavaScript error.

### Observed
It does:
Screenshot 2021-05-04 at 12 44 18
Screenshot 2021-05-04 at 12 44 55

### Reproduced
1. Be logged in
2. Log out

### Where did you see the bug
- System Make: MBP 16"
- OS: Win10 (Parallels) | Big Sur 11.2.3
- Simplenote app version: desktop 2.11.0-beta1

### PR DESCRIPTION
**Pull request by sandymcfadden**
### Fix

Fixes #2888

When setting the Electron `nativeTheme` with the theme selected in the Simplenote settings it can cause a JavaScript error if the theme setting isn't present, such as when logging out of the app.

This checks to ensure the theme setting is set before updating the Electron `nativeTheme` setting.

### Test

1. Ensure you are logged in
2. Log out.
3. Ensure no error appears.

### Release
NA

### CODE REVIEW

File: desktop/app.js [hunk 1]
```diff
@@ -103,7 +103,9 @@ module.exports = function main() {
       Menu.setApplicationMenu(
         Menu.buildFromTemplate(createMenuTemplate(args), mainWindow)
       );
-      nativeTheme.themeSource = settings.theme;
+      if ('theme' in settings) {
```
Comment (belcherj) [inline desktop/app.js:106]: Just want to make sure you know the implications of using `in` over `hasOwnProperty`. In does not care if that property is directly on the object or inherited. There are also some other differences. This seems like a pretty good [article](https://masteringjs.io/tutorials/fundamentals/hasownproperty). (I only skimmed it)

In this case the use of `in` is fine.

**Review by belcherj — APPROVED** [review]

File: desktop/app.js (hunk 1 above)
Comment (sandymcfadden) [reply desktop/app.js:106]: Thank you!

**Comment by mokagio** [comment]
This went into the release branch after beta1 shipped. Should we ship a new beta?

From the milestone list I can see there's nothing else open, so I'd say yes, but thought I'd check first. I'm asking because shipping a new beta involves a bit of manual labor still, so just trying to be efficient 😄 

cc @pachlava

**Comment by sandymcfadden** [comment]
Thanks @mokagio there is one more I'd like to get in. I hadn't updated the milestone yet but I have now https://github.com/Automattic/simplenote-electron/issues/2889
I'd say once that fix goes in I can create the new beta.

**Comment by mokagio** [comment]
👍 thanks @sandymcfadden
