### PR TITLE
Fix: Broken oAuth flow

### LINKED ISSUE #1229: Simplenote users not able to log in with WordPress.com account on Mac, Windows, Linux
Two reports so far for Linux (reproducible on Mac and Windows as well)
Ubuntu 18.10 with 4.18 kernel. Simplenote 1.5.0
Linux Mint and Manjaro. Both are the latest LTS version

I can reproduce this on the Electron Mac version as well, and there is a report for Windows, so it's all 3 Electron apps.

#### Steps to reproduce
1. Try to sign in via WordPress.com on Linux Simplenote app
2. Sign in, click Auth

#### What happened
Linux: "the authorization gets stuck when after clicking "Authorize" button"
Linux: "It goes berserk and issues thousands of requests to `auth`"
Mac Electron: for me, nothing happens at all

#### Simplenote version
1.5.0 (is not an issue in 1.4.1)

### **WORKAROUND**:
You can still log into the Simplenote app with your account details, using your email address and password used to originally sign up.

### PR DESCRIPTION
**Pull request by dmsnell**
Resolves #1229 

We have been experiencing problems when trying to login with the
WordPress.com signin. Something appears to have changed in Electron such
that the older versions of the app still work but newer versions are
failing.

In this patch we're rewriting the authentication flow to simplify it and
prepare ourselves for better handling of the failure cases.

In production we are seeing strange behaviors on failure and some on
success: unending re-requests to `simplenote://auth` which trigger full
CPU load; and no response after authentication.

After this patch we should be able to wrangle in errors and add a
timeout to better communicate when things are failing.

Additionally, the unending loop should be closed due to a replacement of
the old network intercept code with a single simplified model.

---

## Testing

This feature isn't currently working on the `history-analyst-dad` application
configured by default in this repository. In order to test the app you'll have to
build it with a custom `config-local.json` including the details to connect to
the actual production Simplenote system.

 - Logged in with my normal WordPress.com account ✅
 - Created a new WordPress.com account but didn't verify my email address, tried to login here and it failed, responding with a message indicating as much. ✅

 - Logging in to WordPress.com with a non-production app (`history-analyst-dad`) successfully authenticates via oAuth and returns my production-app Simperium token, but that fails when logging in but there's no message. ⭕️ (This is probably best scoped for a separate update as this has been the case before this PR existed and it's not a customer-facing issue, mostly for devs)

### CODE REVIEW

File: lib/auth/index.jsx [hunk 1]
```diff
@@ -216,84 +216,73 @@ export class Auth extends Component {
...
-          return this.authError('An error was encountered while signing in.');
+    this.authWindow.webContents.session.protocol.registerHttpProtocol(
+      'simplenote',
+      (req, callback) => {
+        const { searchParams } = new URL(req.url);
+
+        // cancel the request by running callback() with no parameters
+        // we're going to close the window and continue processing the
+        // information we received in args of the simplenote://auth URL
+        callback();
```
Comment (roundhill) [inline lib/auth/index.jsx]: So this is what fixed the looping issue?

Comment (dmsnell) [reply lib/auth/index.jsx]: I believe so, that and our manual redirect.
