### PR TITLE
Tracks: Opt Out

### LINKED ISSUE #404: How do I disable Developer Telemetry?
It appears to me that every time I search, on top of the API call, there is an additional query to pixel.wp.com. I understand that developer telemetry is normal practice, but most applications allow users to opt out.
1. Can anyone verify the same behaviour _(i.e. to confirm my install is not broken or something)_
2. Is there a privacy setting somewhere that I've missed?
#### Steps to reproduce
1. Install Simplenote and log-in, then exit
2. Open Fiddler or Wireshark, start network capture
3. Open Simplenote
4. Search for something
5. Observe/Capture requests to pixel.wp.com
#### OS version
- Windows 10 (Enterprise) - 64bit - Build 14393.2222 
- Simplenote 1.0.3
#### Fiddler Screenshot

simple_note_telemetry

### LINKED ISSUE #837: Tracks: Opt Out
### Details:
- [ ] Add a new boolean field to the`Settings` entity (Simperium backed) to persist if the user opted out from Tracks
- [ ] Add a new Switch in the Settings UI

Ref. [iOS Issue](https://github.com/Automattic/simplenote-ios/issues/222)

### PR DESCRIPTION
**Pull request by mirka**
Closes #837
Closes #404 

- [x] Add toggle in settings dialog
- [x] Set up the preferences bucket
- [x] Reflect settings in analytics
- [x] Tweak dialog UI

settings dialog ui

### CODE REVIEW

File: lib/boot.js [hunk 1]
```diff
@@ -64,12 +64,15 @@ const client = simperium(
...
+    preferences: function(objectStore) {
+      console.log('Configure preferences', objectStore); // eslint-disable-line no-console
+    },
     tag: function(objectStore) {
       console.log('Configure tag', objectStore); // eslint-disable-line no-console
     },
   },
   'simplenote',
-  40
+  41
```
Comment (roundhill) [inline lib/boot.js]: Can we make this a constant like `dbVersion` or something so that future devs can grok this better?

**Comment by roundhill** [comment]
Looking pretty good, I sent a few fixes via Slack. Also, we need to see if the iOS/macOS apps can get fixed from sending `1/0` instead of `true/false`. If it can't get fixed we'll need to set 0/1 from all of the other clients instead of a boolean :(

Ref: https://github.com/Automattic/simplenote-ios/pull/228#issuecomment-422970461

File: lib/boot.js (hunk 1 above)
Comment (mirka) [reply lib/boot.js]: Good point. There are a lot of arguments here, so I changed it into an object to make it clearer all around. 95f94cd

File: lib/flux/app-state.js [hunk 2]
```diff
@@ -700,19 +700,32 @@ export const actionMap = new ActionMap({
...
-              );
+          preferencesBucket.get(objectKey, (e, preferences) => {
+            const preferencesData = preferences ? preferences.data : {};
+            const {
+              analytics_enabled: analyticsEnabled = true,
+            } = preferencesData;
+
+            // Create empty preferences object in the bucket if not yet there
+            if (preferences === undefined) {
+              preferencesBucket.update(objectKey, preferencesData);
```
Comment (mirka) [inline lib/flux/app-state.js]: I added a few steps in here to make sure a `preferences-key` object is created if it doesn't exist yet.

File: lib/flux/app-state.js [hunk 3]
```diff
@@ -696,6 +696,78 @@ export const actionMap = new ActionMap({
...
+
+    loadPreferences: {
+      creator({ callback, preferencesBucket }) {
+        return dispatch => {
+          const objectKey = 'preferences-key';
+
+          preferencesBucket.get(objectKey, (e, preferences) => {
+            const preferencesData = preferences ? preferences.data : {};
+            const {
+              analytics_enabled: analyticsEnabled = true,
```
Comment (roundhill) [inline lib/flux/app-state.js]: Unfortunately we need to check if this is either a boolean or a int value of `0` or `1` because of how iOS saves the boolean value (it won't be fixed in the near future). We can still save it as a boolean because iOS can read the value properly still.

Comment (mirka) [reply lib/flux/app-state.js]: Added a step to cast it to a boolean 👍

Comment (roundhill) [reply lib/flux/app-state.js]: Javascript can be so magical sometimes ❤️

File: lib/flux/app-state.js [hunk 4]
```diff
@@ -696,6 +696,79 @@ export const actionMap = new ActionMap({
...
       });
     },
+
+    loadPreferences: {
+      creator({ callback, preferencesBucket }) {
+        return dispatch => {
+          const objectKey = 'preferences-key';
+
+          preferencesBucket.get(objectKey, (e, preferences) => {
+            const preferencesData = preferences ? preferences.data : {};
```
Comment (roundhill) [inline lib/flux/app-state.js]: Suggestion: This might be a nice place to use `lodash`'s `get` method: https://lodash.com/docs/4.17.10#get

something like `get(preferences, 'data.analytics_enabled', true)`?

Comment (mirka) [reply lib/flux/app-state.js]: Thanks! I'm not yet familiar with all the lodash functions, so please keep these suggestions coming 🙂

Comment (roundhill) [reply lib/flux/app-state.js]: Nice! Change looks good 👍
